

#' Train a K-cell-type ctOWAS prediction model
#'
#' Trains a cell-type-specific molecular prediction model for one gene or
#' protein using genotype data, estimated cell-type fractions, and optional
#' covariates. The method first performs repeated split-sample stability
#' screening to identify cell-type-specific SNP predictors and then fits an
#' elastic-net model using the selected predictors.
#'
#' @param y A numeric vector or one-column matrix of length N containing the
#'   molecular phenotype for one gene or protein.
#' @param x A numeric N by P genotype dosage matrix, where rows represent
#'   samples and columns represent cis-SNPs.
#' @param cov An optional numeric N by Q covariate matrix. If \code{NULL}, no
#'   covariates are included.
#' @param pi_k A numeric N by K matrix of estimated cell-type fractions. Rows
#'   represent samples and columns represent cell types. Fractions in each row
#'   should typically sum approximately to one.
#' @param xNameMatrix Optional SNP annotation with P rows. The first column must
#'   contain SNP identifiers in the same order as the columns of \code{x}. If
#'   \code{NULL}, identifiers are taken from \code{colnames(x)} or generated as
#'   \code{SNP1}, \code{SNP2}, and so forth.
#' @param yName Optional gene or protein identifier returned with the fitted
#'   model.
#' @param foldid Optional integer vector of length N assigning samples to
#'   cross-validation folds. If \code{NULL}, randomized 10-fold assignments are
#'   generated.
#' @param fdr_min Minimum candidate FDR threshold used by the adaptive predictor
#'   screening procedure.
#' @param fdr_max Maximum candidate FDR threshold used by the adaptive predictor
#'   screening procedure.
#' @param min_predictors Minimum number of cell-type-specific SNP coefficients
#'   that the adaptive FDR threshold attempts to retain.
#' @param alpha Elastic-net mixing parameter passed to \code{glmnet}. A value of
#'   zero corresponds to ridge regression and a value of one corresponds to
#'   lasso regression. The default is \code{0.5}.
#' @param seed Optional integer random seed controlling cross-validation fold
#'   generation and repeated sample splitting. If \code{NULL}, the existing R
#'   random-number state is used.
#'
#' @details
#' For K cell types, the cell-type-expanded design matrix contains a separate
#' intercept and a separate set of P SNP coefficients for each cell type. For
#' sample i and cell type k, the corresponding design block is
#'
#' \deqn{\pi_{ik}(1, x_{i1}, \ldots, x_{iP}),}
#'
#' where \eqn{\pi_{ik}} is the estimated fraction of cell type k and
#' \eqn{x_{ij}} is the dosage of SNP j.
#'
#' Predictor screening begins by selecting a ridge-regression penalty through
#' cross-validation. The samples are then randomly divided into two subsets in
#' each of 11 iterations, and the model is fitted separately in the two subsets.
#' For each cell-type-specific SNP coefficient, agreement in direction and
#' magnitude between the two fits is summarized as
#'
#' \deqn{M = \operatorname{sign}(\hat\beta_1)
#'              \operatorname{sign}(\hat\beta_2)
#'              (|\hat\beta_1| + |\hat\beta_2|).}
#'
#' Positive values indicate directionally consistent effects, whereas negative
#' values indicate inconsistent effects. Predictor-level empirical FDR
#' estimates are averaged across the 11 splits. The smallest candidate FDR
#' threshold retaining at least \code{min_predictors} coefficients is selected,
#' subject to \code{fdr_min} and \code{fdr_max}.
#'
#' All K cell-type intercepts, selected cell-type-specific SNP predictors, and
#' supplied covariates are included in the final elastic-net model. The penalty
#' is selected using cross-validation.
#'
#' @return A list with the following components:
#' \describe{
#'   \item{intercept}{A numeric vector of length K containing the fitted
#'     cell-type-specific intercepts.}
#'   \item{W}{A numeric P by K matrix of cell-type-specific SNP weights. SNP
#'     coefficients not selected during screening are represented by zero.}
#'   \item{beta.all.models}{A coefficient matrix containing the cell-type-specific
#'     intercepts, SNP coefficients, and, when supplied, covariate coefficients.}
#'   \item{yName}{The gene or protein identifier supplied through
#'     \code{yName}.}
#'   \item{xNameMatrix}{The SNP annotation supplied to or generated by the
#'     function.}
#'   \item{fdrcut}{The adaptive FDR threshold used to select predictors.}
#'   \item{Num_SNP_input}{The number of input SNPs, P.}
#'   \item{Num_SNP_model}{The number of selected cell-type-specific SNP
#'     coefficients. Because one SNP may be selected for multiple cell types,
#'     this value is not necessarily the number of unique selected SNPs.}
#' }
#'
#' @importFrom glmnet cv.glmnet glmnet
#' @export

ctOWAS_train_K <- function(y, x, cov = NULL, pi_k,xNameMatrix = NULL, yName = NULL,
                            foldid = NULL, fdr_min=0.1, min_predictors=2L,
                            alpha=0.5, num_split=11, seed=NULL) {

  ## ---- Input checks and setup ----
  y    <- as.matrix(y)
  x    <- as.matrix(x)
  pi_k <- as.matrix(pi_k)

  n <- nrow(x)
  p <- ncol(x)
  K <- ncol(pi_k)
  if (is.null(cov)) {pcov <- 0L} else {pcov <- ncol(cov)}

  if (nrow(pi_k) != n) { stop("pi_k must have the same number of rows as x (samples).")}

  # Use supplied SNP annotation, or create a simple fallback label set.
  if (is.null(xNameMatrix)) {
    if (!is.null(colnames(x))) {xNameMatrix <- data.frame(SNP = colnames(x), stringsAsFactors = FALSE)} else {xNameMatrix <- data.frame(SNP = paste0("SNP", seq_len(p)),stringsAsFactors = FALSE)}
  }

  # fix randomness
  set.seed(seed)
  if (is.null(foldid)) {foldid <- sample(rep(1:10, length.out = n))}


  ## ---- Create cell-type-level model design matrix ----
  XK <- do.call(cbind, lapply(seq_len(K), \(i) cbind(1, x) * pi_k[, i]))
  if (is.null(cov)) {XX <- XK} else {cov=as.matrix(cov); XX <- cbind(XK, cov)}

  # ------- add random split of the data into two components to identify important predictors ----------
  penalty_factor <- rep(c(0, rep(1, ncol(x))), K)
  if (!is.null(cov)) penalty_factor <- c(penalty_factor, rep(1, ncol(cov)))

  idx=sample(rep(1:2, length.out = n))
  ft11 <- ft11 <- glmnet::cv.glmnet(x = XX[idx==1,], y = y[idx==1,],family= "gaussian",
    alpha= alpha,
    penalty.factor = penalty_factor,
    intercept = F)
  lambda_cell <- ft11$lambda.1se

  fdr=NULL
  for (split in 1:num_split) {
    idx=sample(rep(1:2, length.out = n))
    ft1 <- glmnet::glmnet(XX[idx == 1, ], y[idx == 1], family = "gaussian", lambda = lambda_cell,
                          penalty.factor = penalty_factor, alpha = alpha, intercept = FALSE)

    selected <- which(as.numeric(coef(ft1))[-1] != 0)
    ols1 <- lm(y[idx == 2] ~ XX[idx == 2, selected, drop = FALSE]-1)
    beta1_refit <- numeric(ncol(XX)); beta1_refit[selected] <- coef(ols1)

    ft2 <- glmnet::glmnet(x = XX[idx==2,], y = y[idx==2,], family= "gaussian", lambda = lambda_cell,
                          penalty.factor = penalty_factor, alpha  = alpha,intercept = FALSE)
    selected <- which(as.numeric(coef(ft2))[-1] != 0)
    ols2 <- lm(y[idx == 1] ~ XX[idx == 1, selected, drop = FALSE]-1)
    beta2_refit <- numeric(ncol(XX)); beta2_refit[selected] <- coef(ols2)

    M1 <- sign(beta1_refit *beta2_refit) * pmin(abs(beta1_refit), abs(beta2_refit))
    m1 <- as.numeric(M1)[setdiff(seq_len((p + 1L) * K), seq(1L, (p + 1L) * K, by = p + 1L))]


    fdr1 <- rep(1, length(m1))
    thresholds <- sort(unique(m1[is.finite(m1) & m1 > 0]))

    if (length(thresholds)) {
      raw_fdr <- vapply(thresholds, \(t)
                        min(1, (0.01 + sum(m1 <= -t, na.rm = TRUE)) / max(sum(m1 >=  t, na.rm = TRUE), 1L)), numeric(1))
      fdr1[is.finite(m1) & m1 > 0] <- raw_fdr[match(m1[is.finite(m1) & m1 > 0], thresholds)]
    }

    fdr=cbind(fdr, fdr1)
  }
  fdr_mean=apply(fdr, 1, mean)

  # ------- fit only significant input --------------

  idx_intercept <- (seq_len(K) - 1L) * (p + 1L) + 1L
  idx_x <- unlist(lapply(seq_len(K), \(k) (k - 1L) * (p + 1L) + seq.int(min_predictors, p + 1L)))
  selected_x <- union(which(fdr_mean < fdr_min), head(order(fdr_mean), min(2L, p)))
  idx_XK <- sort(c(idx_intercept, idx_x[selected_x]))
  idx_XX = c(idx_XK, if (!is.null(cov)) (p+1L)*K + seq_len(ncol(cov)))

  coef_no_intercept <- rep(0, ncol(XX))

  if (length(idx_XK)>0) {

    XX_selected <- XX[, idx_XX, drop = FALSE]
    penalty_factor_selected <- penalty_factor[idx_XX]

    # print("Passed screening")
    ft11 <- glmnet::cv.glmnet(x = XX_selected, y = y,
      family         = "gaussian",
      foldid         = foldid,
      alpha          = alpha,
      penalty_factor=penalty_factor_selected,
      intercept = FALSE)
    lambda_cell <- ft11$lambda.1se

    ft <- glmnet::glmnet( x = XX_selected, y = y, family = "gaussian",
                          lambda = lambda_cell, alpha = alpha,penalty_factor=penalty_factor_selected,
                          intercept = FALSE)
    coef_no_intercept[idx_XX] <- as.numeric(ft$beta)[seq_along(idx_XX)]

  }
  if (length(idx_XK)==0) {return(NULL)}


  ## ---- Harvest results ----

  coef_cell=matrix(coef_no_intercept[1:(K*(1L+p))], ncol=K)
  if (is.null(cov)==F) {
    cov_block <- do.call(cbind, replicate(K, coef_no_intercept[(K*p+K+1L):ncol(XX)], simplify = FALSE))
    coef_cell=rbind(coef_cell, cov_block)
  }
  colnames(coef_cell) <- paste0("Cell", seq_len(K))

  if (is.null(cov)) {
    rownames(coef_cell)=c("intercept", xNameMatrix[[1]])
  } else { rownames(coef_cell)=c("intercept", xNameMatrix[[1]], colnames(cov))}

  a_cell <- coef_cell[1,] # length K
  B_mat = coef_cell[2:(p+1),]

  ## ---- Classify the fitted model ----

  list(
    intercept        = a_cell,
    W                = B_mat,
    beta.all.models  = coef_cell,
    yName            = yName,
    xNameMatrix      = xNameMatrix
  )

}

