#' Train a K-cell-type ctOWAS prediction model
#'
#' Trains a cell-type-specific molecular prediction model for one gene or
#' protein using genotype data, estimated cell-type fractions, and optional
#' covariates. The method first performs repeated split-sample stability
#' screening to identify cell-type-specific SNP predictors and then fits an
#' elastic-net model using the selected predictors.
#'
#' @param y A numeric vector or one-column matrix of length N containing the
#'   molecular phenotype for one gene or protein.
#' @param x A numeric N by P genotype dosage matrix, where rows represent
#'   samples and columns represent cis-SNPs.
#' @param cov An optional numeric N by Q covariate matrix. If \code{NULL}, no
#'   covariates are included.
#' @param pi_k A numeric N by K matrix of estimated cell-type fractions. Rows
#'   represent samples and columns represent cell types. Fractions in each row
#'   should typically sum approximately to one.
#' @param xNameMatrix Optional SNP annotation with P rows. The first column must
#'   contain SNP identifiers in the same order as the columns of \code{x}. If
#'   \code{NULL}, identifiers are taken from \code{colnames(x)} or generated as
#'   \code{SNP1}, \code{SNP2}, and so forth.
#' @param yName Optional gene or protein identifier returned with the fitted
#'   model.
#' @param foldid Optional integer vector of length N assigning samples to
#'   cross-validation folds. If \code{NULL}, randomized 10-fold assignments are
#'   generated.
#' @param fdr_min Minimum candidate FDR threshold used by the adaptive predictor
#'   screening procedure.
#' @param min_predictors Minimum number of unique SNPs retained. All mean and
#'   contrast terms at or below fdr_min are retained first; if these represent
#'   fewer SNPs, the best remaining SNPs are added by minimum FDR.
#' @param alpha Elastic-net mixing parameter passed to \code{glmnet}. A value of
#'   zero corresponds to ridge regression and a value of one corresponds to
#'   lasso regression. The default is \code{0.5}.
#' @param seed Optional integer random seed controlling cross-validation fold
#'   generation and repeated sample splitting. If \code{NULL}, the existing R
#'   random-number state is used.
#'
#' @details
#' For K cell types, the cell-type-expanded design matrix contains a separate
#' intercept and a separate set of P SNP coefficients for each cell type. For
#' sample i and cell type k, the corresponding design block is
#'
#' \deqn{\pi_{ik}(1, x_{i1}, \ldots, x_{iP}),}
#'
#' where \eqn{\pi_{ik}} is the estimated fraction of cell type k and
#' \eqn{x_{ij}} is the dosage of SNP j.
#'
#' Predictor screening begins by selecting a ridge-regression penalty through
#' cross-validation. The samples are then randomly divided into two subsets in
#' each of 11 iterations, and the model is fitted separately in the two subsets.
#' For each cell-type-specific SNP coefficient, agreement in direction and
#' magnitude between the two fits is summarized as
#'
#' \deqn{M = \operatorname{sign}(\hat\beta_1)
#'              \operatorname{sign}(\hat\beta_2)
#'              (|\hat\beta_1| + |\hat\beta_2|).}
#'
#' Positive values indicate directionally consistent effects, whereas negative
#' values indicate inconsistent effects. Predictor-level empirical FDR
#' estimates are averaged across the repeated splits. All qualifying terms at
#' or below \code{fdr_min} are retained, with the lowest-FDR remaining SNPs
#' added when needed to satisfy \code{min_predictors}.
#'
#' All K cell-type intercepts, selected cell-type-specific SNP predictors, and
#' supplied covariates are included in the final elastic-net model. The penalty
#' is selected using cross-validation.
#'
#' @return A list with the following components:
#' \describe{
#'   \item{intercept}{A numeric vector of length K containing the fitted
#'     cell-type-specific intercepts.}
#'   \item{W}{A numeric P by K matrix of cell-type-specific SNP weights. SNP
#'     coefficients not selected during screening are represented by zero.}
#'   \item{beta.all.models}{A coefficient matrix containing the cell-type-specific
#'     intercepts, SNP coefficients, and, when supplied, covariate coefficients.}
#'   \item{yName}{The gene or protein identifier supplied through
#'     \code{yName}.}
#'   \item{xNameMatrix}{The SNP annotation supplied to or generated by the
#'     function.}
#'   \item{fdrcut}{The adaptive FDR threshold used to select predictors.}
#'   \item{Num_SNP_input}{The number of input SNPs, P.}
#'   \item{Num_SNP_model}{The number of unique selected SNPs.}
#'   \item{Num_effect_model}{The number of selected mean/contrast SNP terms.}
#' }
#'
#' @importFrom glmnet cv.glmnet glmnet
#' @export

ctOWAS_train_K <- function(y, x, cov = NULL, pi_k,xNameMatrix = NULL, yName = NULL,
                           foldid = NULL,
                           fdr_min=0.1, min_predictors=2L, num_split=11,
                           alpha=0.5, seed=NULL) {


  # Fix randomness when a seed is supplied.
  if (!is.null(seed)) set.seed(seed)
  if (is.null(foldid)) {foldid <- sample(rep(1:10, length.out = n))}

  ## ---- Input checks and setup ----
  y    <- as.matrix(y)
  x    <- as.matrix(x)
  pi_k <- as.matrix(pi_k)

  n <- nrow(x)
  p <- ncol(x)
  K <- ncol(pi_k)
  if (is.null(cov)) {pcov <- 0L} else {pcov <- ncol(cov)}

  if (nrow(pi_k) != n) { stop("pi_k must have the same number of rows as x (samples).")}

  # Use supplied SNP annotation, or create a simple fallback label set.
  if (is.null(xNameMatrix)) {
    if (!is.null(colnames(x))) {xNameMatrix <- data.frame(SNP = colnames(x), stringsAsFactors = FALSE)} else {xNameMatrix <- data.frame(SNP = paste0("SNP", seq_len(p)),stringsAsFactors = FALSE)}
  }

  ## ---- Create mean/contrast model design matrix ----
  # C is K x (K-1). T maps mean/contrast coefficients to K cell types.
  C <- stats::contr.helmert(K)
  T_mat <- cbind(Mean = 1, C)
  c_mat <- pi_k %*% C
  Z_block <- do.call(cbind, lapply(seq_len(K - 1L), \(m) c_mat[, m] * x))

  if (!is.null(cov)) {
    cov <- stats::model.matrix(
      ~ . - 1,
      data = as.data.frame(cov)
    )
    storage.mode(cov) <- "double"
    pcov <- ncol(cov)
  }

  XX <- cbind(c_mat, x, Z_block, if (!is.null(cov)) cov)
  XX <- as.matrix(XX)
  storage.mode(XX) <- "double"

  # Column layout in XX:
  #   1:(K-1)                              intercept contrasts
  #   K:(K-1+p)                            mean SNP effects
  #   (K+p):(K-1+p+p*(K-1))                contrast SNP effects
  #   (K*(p+1)):ncol(XX)                    optional covariates
  # The cell-type mean intercept is glmnet's unpenalized intercept (a0).
  n_model <- K * (p + 1L) - 1L
  idx_intercept <- seq_len(K - 1L)
  idx_x_mean <- K - 1L + seq_len(p)
  idx_x_contrast <- K - 1L + p + seq_len(p * (K - 1L))
  idx_x <- c(idx_x_mean, idx_x_contrast)
  idx_cov <- if (pcov > 0L) n_model + seq_len(pcov) else integer()

  # ------- add random split of the data into two components to identify important predictors ----------
  penalty_factor <- rep(1, ncol(XX))
  penalty_factor[idx_intercept] <- 0

  idx=sample(rep(1:2, length.out = n))
  ft11 <- glmnet::cv.glmnet(
    x = XX[idx==1,], y = y[idx==1,],
    family         = "gaussian",
    alpha          = alpha,
    penalty.factor = penalty_factor,
    intercept = TRUE
  )
  lambda_cell <- ft11$lambda.1se

  fdr=NULL
  for (split in 1:num_split) {

    idx=sample(rep(1:2, length.out = n))

    ft1 <- glmnet::glmnet(XX[idx == 1, ], y[idx == 1], family = "gaussian", lambda = lambda_cell,
                          penalty.factor = penalty_factor, alpha = alpha, intercept = TRUE)

    selected <- which(as.numeric(coef(ft1))[-1] != 0)
    ols1 <- lm(y[idx == 2] ~ XX[idx == 2, selected, drop = FALSE])
    beta1_refit <- numeric(ncol(XX)); beta1_refit[selected] <- coef(ols1)[-1]

    ft2 <- glmnet::glmnet(x = XX[idx==2,], y = y[idx==2,], family= "gaussian", lambda = lambda_cell,
                          penalty.factor = penalty_factor, alpha  = alpha,intercept = TRUE)
    selected <- which(as.numeric(coef(ft2))[-1] != 0)
    ols2 <- lm(y[idx == 1] ~ XX[idx == 1, selected, drop = FALSE])
    beta2_refit <- numeric(ncol(XX)); beta2_refit[selected] <- coef(ols2)[-1]

    M1 <- sign(beta1_refit *beta2_refit) * pmin(abs(beta1_refit), abs(beta2_refit))
    m <- as.numeric(M1)[K:(K-1+p+p*(K-1))]
    m_mat <- matrix(m, nrow = p, ncol = K)
    #


    fdr_mat <- apply(m_mat, 2L, function(z) {
      fdr <- rep(1, length(z))
      thresholds <- sort(unique(z[is.finite(z) & z > 0]))

      if (!length(thresholds)) return(fdr)

      raw_fdr <- vapply(thresholds, \(t)
                        min(1, (0.01 + sum(z <= -t, na.rm = TRUE)) /
                              max(sum(z >= t, na.rm = TRUE), 1L)),
                        numeric(1)
      )

      i <- which(is.finite(z) & z > 0)
      fdr[i] <- cummin(raw_fdr)[findInterval(z[i], thresholds)]
      fdr
    })

    # Same ordering as m: p mean effects, then p effects per contrast
    fdr1 <- as.vector(fdr_mat)

    fdr=cbind(fdr, fdr1)
  }
  fdr_mean=apply(fdr, 1, mean)
  fdr_mean[!is.finite(fdr_mean)] <- 1
  fdr_mean[fdr_mean>1]=1

  # ------- fit only significant input --------------


  # Keep every term below fdr_min, then ensure at least min_predictors unique SNPs.
  fdr_x <- matrix(fdr_mean, nrow = p, ncol = K)
  selected_x <- fdr_x <= fdr_min
  selected_snps <- which(rowSums(selected_x) > 0L)
  target_snps <- max(as.integer(min_predictors), length(selected_snps))


  if (length(selected_snps) < target_snps) {
    best_fdr <- apply(fdr_x, 1L, min)
    add_snps <- head(setdiff(order(best_fdr), selected_snps),target_snps - length(selected_snps))
    selected_snps <- c(selected_snps, add_snps)
  }

  # Keep both mean and all contrast effects for every selected SNP
  selected_x[,] <- FALSE
  selected_x[selected_snps, ] <- TRUE
  selected_position <- which(as.vector(selected_x))
  idx_x_selected <- idx_x[selected_position]

  nm <- as.character(xNameMatrix[[1]])
  fdr_by_input <- setNames(fdr_mean,
                           c(paste0("mean_", nm),
                             unlist(lapply(seq_len(K - 1L), \(m)
                                           paste0("contrast_", paste(seq_len(m), collapse = "_"), "_",
                                                  m + 1L, "_", nm)))))
  idx_model_selected <- sort(c(idx_intercept, idx_x_selected))
  idx_fit <- c(idx_model_selected, idx_cov)
  XX_selected <- XX[, idx_fit, drop = FALSE]

  coef_design <- rep(0, ncol(XX))
  mean_intercept <- NA_real_

  penalty_factor_selected <- penalty_factor[idx_fit]

  # print("Passed screening")
  ft11 <- glmnet::cv.glmnet( x = XX_selected, y = y,
                               family         = "gaussian",
                               foldid         = foldid,
                               alpha          = alpha,
                               penalty.factor = penalty_factor_selected,
                               intercept = TRUE)
  lambda_cell <- ft11$lambda.1se

  ft <- glmnet::glmnet( x = XX_selected, y = y, family = "gaussian",
                          lambda = lambda_cell, alpha = alpha,
                          penalty.factor = penalty_factor_selected,
                          intercept = TRUE)
  mean_intercept <- as.numeric(ft$a0)
  coef_design[idx_fit] <- as.numeric(ft$beta)[seq_along(idx_fit)]



  ## ---- Harvest results ----

  theta_intercept <- c(mean_intercept, coef_design[idx_intercept])
  theta_snp <- cbind(
    Mean = coef_design[idx_x_mean],
    matrix(coef_design[idx_x_contrast], nrow = p, ncol = K - 1L)
  )

  # Transform mean/contrast coefficients back to cell-type coefficients.
  a_cell <- as.numeric(T_mat %*% theta_intercept)
  B_mat <- theta_snp %*% t(T_mat)
  coef_cell <- rbind(a_cell, B_mat)

  if (pcov > 0L) {
    cov_block <- matrix(coef_design[idx_cov], nrow = pcov, ncol = K)
    coef_cell <- rbind(coef_cell, cov_block)
  }
  colnames(coef_cell) <- paste0("Cell", seq_len(K))

  if (is.null(cov)) {
    rownames(coef_cell)=c("intercept", xNameMatrix[[1]])
  } else { rownames(coef_cell)=c("intercept", xNameMatrix[[1]], colnames(cov))}

  a_cell <- coef_cell[1, ]
  B_mat <- coef_cell[seq.int(2L, p + 1L), , drop = FALSE]

  ## ---- Classify the fitted model ----

  list(
    intercept        = a_cell,
    W                = B_mat,
    beta.all.models  = coef_cell,
    yName            = yName,
    xNameMatrix      = xNameMatrix,
    fdr_by_input = fdr_by_input,
    Num_SNP_input = p,
    Num_SNP_model=sum(rowSums(B_mat) > 0L))

}
