

#' Train a K-cell-type ctOWAS prediction model
#'
#' Trains a cell-type-specific molecular prediction model for one gene or
#' protein using genotype data, estimated cell-type fractions, and optional
#' covariates. The method first performs repeated split-sample stability
#' screening to identify cell-type-specific SNP predictors and then fits an
#' elastic-net model using the selected predictors.
#'
#' @param y A numeric vector or one-column matrix of length N containing the
#'   molecular phenotype for one gene or protein.
#' @param x A numeric N by P genotype dosage matrix, where rows represent
#'   samples and columns represent cis-SNPs.
#' @param cov An optional numeric N by Q covariate matrix. If \code{NULL}, no
#'   covariates are included.
#' @param pi_k A numeric N by K matrix of estimated cell-type fractions. Rows
#'   represent samples and columns represent cell types. Fractions in each row
#'   should typically sum approximately to one.
#' @param xNameMatrix Optional SNP annotation with P rows. The first column must
#'   contain SNP identifiers in the same order as the columns of \code{x}. If
#'   \code{NULL}, identifiers are taken from \code{colnames(x)} or generated as
#'   \code{SNP1}, \code{SNP2}, and so forth.
#' @param yName Optional gene or protein identifier returned with the fitted
#'   model.
#' @param foldid Optional integer vector of length N assigning samples to
#'   cross-validation folds. If \code{NULL}, randomized 10-fold assignments are
#'   generated.
#' @param fdr_min Minimum candidate FDR threshold used by the adaptive predictor
#'   screening procedure.
#' @param fdr_max Maximum candidate FDR threshold used by the adaptive predictor
#'   screening procedure.
#' @param min_predictors Minimum number of cell-type-specific SNP coefficients
#'   that the adaptive FDR threshold attempts to retain.
#' @param alpha Elastic-net mixing parameter passed to \code{glmnet}. A value of
#'   zero corresponds to ridge regression and a value of one corresponds to
#'   lasso regression. The default is \code{0.5}.
#' @param seed Optional integer random seed controlling cross-validation fold
#'   generation and repeated sample splitting. If \code{NULL}, the existing R
#'   random-number state is used.
#'
#' @details
#' For K cell types, the cell-type-expanded design matrix contains a separate
#' intercept and a separate set of P SNP coefficients for each cell type. For
#' sample i and cell type k, the corresponding design block is
#'
#' \deqn{\pi_{ik}(1, x_{i1}, \ldots, x_{iP}),}
#'
#' where \eqn{\pi_{ik}} is the estimated fraction of cell type k and
#' \eqn{x_{ij}} is the dosage of SNP j.
#'
#' Predictor screening begins by selecting a ridge-regression penalty through
#' cross-validation. The samples are then randomly divided into two subsets in
#' each of 11 iterations, and the model is fitted separately in the two subsets.
#' For each cell-type-specific SNP coefficient, agreement in direction and
#' magnitude between the two fits is summarized as
#'
#' \deqn{M = \operatorname{sign}(\hat\beta_1)
#'              \operatorname{sign}(\hat\beta_2)
#'              (|\hat\beta_1| + |\hat\beta_2|).}
#'
#' Positive values indicate directionally consistent effects, whereas negative
#' values indicate inconsistent effects. Predictor-level empirical FDR
#' estimates are averaged across the 11 splits. The smallest candidate FDR
#' threshold retaining at least \code{min_predictors} coefficients is selected,
#' subject to \code{fdr_min} and \code{fdr_max}.
#'
#' All K cell-type intercepts, selected cell-type-specific SNP predictors, and
#' supplied covariates are included in the final elastic-net model. The penalty
#' is selected using cross-validation.
#'
#' @return A list with the following components:
#' \describe{
#'   \item{intercept}{A numeric vector of length K containing the fitted
#'     cell-type-specific intercepts.}
#'   \item{W}{A numeric P by K matrix of cell-type-specific SNP weights. SNP
#'     coefficients not selected during screening are represented by zero.}
#'   \item{beta.all.models}{A coefficient matrix containing the cell-type-specific
#'     intercepts, SNP coefficients, and, when supplied, covariate coefficients.}
#'   \item{yName}{The gene or protein identifier supplied through
#'     \code{yName}.}
#'   \item{xNameMatrix}{The SNP annotation supplied to or generated by the
#'     function.}
#'   \item{fdrcut}{The adaptive FDR threshold used to select predictors.}
#'   \item{Num_SNP_input}{The number of input SNPs, P.}
#'   \item{Num_SNP_model}{The number of selected cell-type-specific SNP
#'     coefficients. Because one SNP may be selected for multiple cell types,
#'     this value is not necessarily the number of unique selected SNPs.}
#' }
#'
#' @importFrom glmnet cv.glmnet glmnet
#' @export

ctOWAS_train_K <- function(y, x, cov = NULL, pi_k,xNameMatrix = NULL, yName = NULL,
                            foldid = NULL,  alpha=0.5, seed=NULL) {

  ## ---- Input checks and setup ----
  y    <- as.matrix(y)
  x    <- as.matrix(x)
  pi_k <- as.matrix(pi_k)

  n <- nrow(x)
  p <- ncol(x)
  K <- ncol(pi_k)
  if (is.null(cov)) {pcov <- 0L} else {pcov <- ncol(cov)}

  if (nrow(pi_k) != n) { stop("pi_k must have the same number of rows as x (samples).")}

  # Use supplied SNP annotation, or create a simple fallback label set.
  if (is.null(xNameMatrix)) {
    if (!is.null(colnames(x))) {xNameMatrix <- data.frame(SNP = colnames(x), stringsAsFactors = FALSE)} else {xNameMatrix <- data.frame(SNP = paste0("SNP", seq_len(p)),stringsAsFactors = FALSE)}
  }

  # fix randomness

  if (is.null(foldid)) {  set.seed(seed); foldid <- sample(rep(1:10, length.out = n))}


  ## ---- Create cell-type-level model design matrix ----
  XK <- do.call(cbind, lapply(seq_len(K), \(i) cbind(1, x) * pi_k[, i]))
  if (is.null(cov)) {XX <- XK} else {cov=as.matrix(cov); XX <- cbind(XK, cov)}

  # ------- add random split of the data into two components to identify important predictors ----------

  ft11 <- glmnet::cv.glmnet(x = XX, y = y,family= "gaussian",foldid= foldid, alpha = alpha,intercept = FALSE)
  lambda_cell <- ft11$lambda.1se

  fdr=NULL
  for (split in 1:11) {

    idx=sample(rep(1:2, length.out = n))
    ft1 <- glmnet::glmnet(
      x = XX[idx==1,], y = y[idx==1,],
      family         = "gaussian",
      lambda         = lambda_cell,
      alpha          = alpha,
      intercept = FALSE
    )
    ft1d <- glmnet::glmnet(
      x = XX[idx==1,], y = y[idx==1,],
      family         = "gaussian",
      lambda         = 0.000001,
      alpha          = 0,
      intercept = FALSE
    ) # direction
    ft2 <- glmnet::glmnet(
      x = XX[idx==2,], y = y[idx==2,],
      family         = "gaussian",
      lambda         = 0.000001,
      alpha          = 0,
      intercept = FALSE
    ) # OLS

    M1 = sign(ft1d$beta)*sign(ft2$beta)*(abs(ft1$beta) + abs(ft2$beta))
    # m1 <- as.numeric(M1)[1: ((p+1L)*K)]

    fdr1 <- vapply(M1, \(x) {
      if (x <= 0) 1
      else sum(M1 < 0 & abs(M1) >= x) / max(sum(M1 >= x),1)
    }, numeric(1))

    fdr=cbind(fdr, fdr1)
  }
  fdr_mean=apply(fdr, 1, mean)
  fdr_mean[which(fdr_mean>1)]=1
  # use fdr_mean as penalty to refit lasso

  ft_w <- glmnet::cv.glmnet(x = XX, y = y,family= "gaussian",foldid= foldid,
                            penalty.factor = fdr_mean, alpha = alpha,intercept = FALSE)
  lambda_cell <- ft_w$lambda.1se
  ft <- glmnet::glmnet( x = XX, y = y, family = "gaussian",
                        lambda = lambda_cell, alpha = alpha, penalty.factor = fdr_mean,
                        intercept = FALSE)

  ## ---- Harvest results ----
  coef_no_intercept <- as.numeric(ft$beta)
  coef_cell=matrix(coef_no_intercept[1:(K*(1L+p))], ncol=K)
  colnames(coef_cell) <- paste0("Cell", seq_len(K))
  rownames(coef_cell) <- c("intercept", xNameMatrix[[1]])

  ## Append common covariate coefficients to every cell-type column
  if (!is.null(cov)) {
    cov_coef <- coef_no_intercept[(K * (p + 1L) + 1L):ncol(XX)]
    coef_cell <- rbind(coef_cell, matrix(cov_coef, ncol = K, nrow = pcov))
    rownames(coef_cell)[(p + 2L):(p + 1L + pcov)] <- colnames(cov)
  }


  a_cell <- coef_cell[1,] # length K
  B_mat  <- coef_cell[2:(p + 1L), , drop = FALSE]

  idx_x_selected <- which(rowSums(abs(B_mat)) > 0)

  list(
    intercept       = a_cell,
    W               = B_mat,
    beta.all.models = coef_cell,
    yName           = yName,
    xNameMatrix     = xNameMatrix,
    fdr.mean        = fdr_mean,
    Num_SNP_input   = p,
    Num_SNP_model   = length(idx_x_selected)
  )

}

